catalogs:
  dev:
    '@eslint/config-inspector': ^1.1.0
    '@types/node': ^22.17.0
    eslint-typegen: ^2.3.0
    tsdown: ^0.13.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    vitest: ^3.2.4
  peer:
    astro-eslint-parser: ^1.2.2
    eslint: ^9.32.0
    eslint-plugin-astro: ^1.3.1
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@stylistic/eslint-plugin': ^5.2.2
    '@typescript-eslint/eslint-plugin': ^8.38.0
    '@typescript-eslint/parser': ^8.38.0
    '@vitest/eslint-plugin': ^1.3.4
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-unused-imports: ^4.1.4
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.3.0
    local-pkg: ^1.1.1

onlyBuiltDependencies:
  - esbuild
