catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
strictPeerDependencies: false
trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar
  - cached-factory

overrides:
  '@eslint-community/eslint-utils': ^4.9.1
  '@typescript-eslint/types': ^8.54.0
  '@typescript-eslint/utils': ^8.54.0
  eslint: ^9.39.2
  tsx: ^4.21.0

catalogs:
  dev:
    '@commitlint/cli': ^20.4.1
    '@commitlint/config-conventional': ^20.4.1
    '@eslint/config-inspector': ^1.4.2
    '@types/node': ^24.10.9
    auto-changelog: ^2.5.0
    eslint-typegen: ^2.3.0
    husky: ^9.1.7
    np: ^11.0.2
    pnpm-workspace-yaml: ^1.5.0
    tsdown: ^0.20.1
    tsx: ^4.21.0
    typescript: ^5.9.3
  inline:
    find-up-simple: ^1.0.1
  peer:
    '@adonisjs/eslint-plugin': ^2.2.1
    '@nuxt/eslint-plugin': ^1.13.0
    '@prettier/plugin-xml': ^3.4.2
    astro-eslint-parser: ^1.2.2
    eslint: ^9.39.2
    eslint-plugin-astro: ^1.5.0
    eslint-plugin-erasable-syntax-only: ^0.4.0
    eslint-plugin-format: ^1.3.1
    prettier-plugin-astro: ^0.14.1
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^1.0.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.6.0
    '@eslint/markdown': ^7.5.1
    '@stylistic/eslint-plugin': ^5.7.1
    '@typescript-eslint/eslint-plugin': ^8.54.0
    '@typescript-eslint/parser': ^8.54.0
    '@vitest/eslint-plugin': ^1.6.6
    ansis: ^4.2.0
    cac: ^6.7.14
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^3.0.0
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.3
    eslint-plugin-command: ^3.4.0
    eslint-plugin-import-lite: ^0.5.0
    eslint-plugin-jsdoc: ^62.5.0
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.2
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^5.4.0
    eslint-plugin-pnpm: ^1.5.0
    eslint-plugin-regexp: ^3.0.0
    eslint-plugin-toml: ^1.0.3
    eslint-plugin-unicorn: ^62.0.0
    eslint-plugin-unused-imports: ^4.3.0
    eslint-plugin-vue: ^10.7.0
    eslint-plugin-yml: ^3.0.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^17.3.0
    jsonc-eslint-parser: ^2.4.2
    local-pkg: ^1.1.2
    parse-gitignore: ^2.0.0
    pathe: ^2.0.3
    toml-eslint-parser: ^1.0.3
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^2.0.0

onlyBuiltDependencies:
  - esbuild
