catalogs:
  dev:
    '@commitlint/cli': ^19.8.1
    '@commitlint/config-conventional': ^19.8.1
    '@eslint/config-inspector': ^1.1.0
    '@types/node': ^22.17.0
    auto-changelog: ^2.5.0
    eslint-typegen: ^2.3.0
    husky: ^9.1.7
    np: ^10.2.0
    tsdown: ^0.13.1
    tsx: ^4.20.3
    typescript: '>=4.8.4 <5.9.0'
  peer:
    '@prettier/plugin-xml': ^3.4.2
    astro-eslint-parser: ^1.2.2
    eslint: ^9.32.0
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-format: ^1.0.1
    prettier-plugin-astro: ^0.14.1
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^7.1.0
    '@stylistic/eslint-plugin': ^5.2.2
    '@typescript-eslint/eslint-plugin': ^8.38.0
    '@typescript-eslint/parser': ^8.38.0
    '@vitest/eslint-plugin': ^1.3.4
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.1
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^52.0.2
    eslint-plugin-jsonc: ^2.20.1
    eslint-plugin-n: ^17.21.3
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.15.0
    eslint-plugin-pnpm: ^1.1.0
    eslint-plugin-regexp: ^2.9.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^60.0.0
    eslint-plugin-unused-imports: ^4.1.4
    eslint-plugin-vue: ^10.4.0
    eslint-plugin-yml: ^1.18.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.3.0
    jsonc-eslint-parser: ^2.4.0
    local-pkg: ^1.1.1
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^1.3.0

onlyBuiltDependencies:
  - esbuild
