catalogs:
  dev:
    '@commitlint/cli': ^20.1.0
    '@commitlint/config-conventional': ^20.0.0
    '@eslint/config-inspector': ^1.3.0
    '@types/node': ^22.18.9
    auto-changelog: ^2.5.0
    eslint-typegen: ^2.3.0
    husky: ^9.1.7
    np: ^10.2.0
    tsdown: 0.15.6
    tsx: ^4.20.6
    typescript: ^5.9.3
  peer:
    '@adonisjs/eslint-plugin': ^2.0.1
    '@nuxt/eslint-plugin': ^1.9.0
    '@prettier/plugin-xml': ^3.4.2
    astro-eslint-parser: ^1.2.2
    eslint: ^9.37.0
    eslint-plugin-astro: ^1.3.1
    eslint-plugin-format: ^1.0.2
    prettier-plugin-astro: ^0.14.1
  prod:
    '@antfu/install-pkg': ^1.1.0
    '@clack/prompts': ^0.11.0
    '@eslint-community/eslint-plugin-eslint-comments': ^4.5.0
    '@eslint/markdown': ^7.4.0
    '@stylistic/eslint-plugin': ^5.4.0
    '@typescript-eslint/eslint-plugin': ^8.46.0
    '@typescript-eslint/parser': ^8.46.0
    '@vitest/eslint-plugin': ^1.3.16
    ansis: ^4.2.0
    cac: ^6.7.14
    eslint-config-flat-gitignore: ^2.1.0
    eslint-flat-config-utils: ^2.1.4
    eslint-merge-processors: ^2.0.0
    eslint-plugin-antfu: ^3.1.1
    eslint-plugin-command: ^3.3.1
    eslint-plugin-import-lite: ^0.3.0
    eslint-plugin-jsdoc: ^61.0.1
    eslint-plugin-jsonc: ^2.21.0
    eslint-plugin-n: ^17.23.1
    eslint-plugin-no-only-tests: ^3.3.0
    eslint-plugin-perfectionist: ^4.15.1
    eslint-plugin-pnpm: ^1.2.0
    eslint-plugin-regexp: ^2.10.0
    eslint-plugin-toml: ^0.12.0
    eslint-plugin-unicorn: ^61.0.2
    eslint-plugin-unused-imports: ^4.2.0
    eslint-plugin-vue: ^10.5.0
    eslint-plugin-yml: ^1.19.0
    eslint-processor-vue-blocks: ^2.0.0
    globals: ^16.4.0
    jsonc-eslint-parser: ^2.4.1
    local-pkg: ^1.1.2
    parse-gitignore: ^2.0.0
    pathe: ^2.0.3
    toml-eslint-parser: ^0.10.0
    vue-eslint-parser: ^10.2.0
    yaml-eslint-parser: ^1.3.0

onlyBuiltDependencies:
  - esbuild
